/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceAccueil.java
 *
 * Created on 17 févr. 2014, 23:26:26
 */

package edu.esprit.gui;

/**
 *
 * @author olfa
 */
public class InterfaceAccueil extends javax.swing.JFrame {

    /** Creates new form InterfaceAccueil */
    public InterfaceAccueil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genererstatistique = new javax.swing.JButton();
        genererrapport = new javax.swing.JButton();
        envoyervoucher = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ajouterdeal = new javax.swing.JButton();
        ajoutercatégorie = new javax.swing.JButton();
        supprimerdeal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        supprimerclient = new javax.swing.JButton();
        ajoutervendeur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        genererstatistique.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genererstatistique.setText("Générer Statistique");

        genererrapport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genererrapport.setText("Générer Rapport");

        envoyervoucher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        envoyervoucher.setText("Envoyer Voucher");
        envoyervoucher.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        envoyervoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyervoucherActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des deals"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajouterdeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ajouterdeal.setText("Ajouter Deal");
        ajouterdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterdealActionPerformed(evt);
            }
        });
        jPanel1.add(ajouterdeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 380, 40));

        ajoutercatégorie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ajoutercatégorie.setText("Ajouter Catégorie");
        jPanel1.add(ajoutercatégorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 78, 380, 36));

        supprimerdeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supprimerdeal.setText("Supprimer Deal");
        jPanel1.add(supprimerdeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 120, 380, 39));

        supprimerclient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supprimerclient.setText("Supprimer Client");

        ajoutervendeur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ajoutervendeur.setText("Ajouter Vendeur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ajoutervendeur, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimerclient, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genererrapport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genererstatistique, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))))
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(envoyervoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genererrapport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimerclient, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(envoyervoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ajoutervendeur, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genererstatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouterdealActionPerformed

    private void envoyervoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyervoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envoyervoucherActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutercatégorie;
    private javax.swing.JButton ajouterdeal;
    private javax.swing.JButton ajoutervendeur;
    private javax.swing.JButton envoyervoucher;
    private javax.swing.JButton genererrapport;
    private javax.swing.JButton genererstatistique;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton supprimerclient;
    private javax.swing.JButton supprimerdeal;
    // End of variables declaration//GEN-END:variables

}
