/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.gui;

import edu.esprit.dao.CategorieDAO;
import edu.esprit.dao.DealDAO;
import edu.esprit.dao.VendeurDAO;
import edu.esprit.entities.Categorie;
import edu.esprit.entities.Deal;
import edu.esprit.entities.Vendeur;
import edu.esprit.metier.DealMetier;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author mohamed amine
 */
public class InterfaceAjouterDeal extends javax.swing.JFrame {
    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form InterfaceAjouterDeal
     */
    public InterfaceAjouterDeal() {
        initComponents();
        remlirVendeur();
        remplirCategorie();
        
   


    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttitre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdetail = new javax.swing.JTextArea();
        txtprix = new javax.swing.JTextField();
        txtprixpromo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcomboboxCategorie = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txtduree = new javax.swing.JTextField();
        txtNbreMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcomboboxVendeur = new javax.swing.JComboBox();
        txtNbreMax = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Infos Deal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Arabic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Title-deal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, -1, 30));

        jLabel2.setText("detail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 80, 40, -1));

        jLabel3.setText("prix");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel4.setText("prix-promo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        jPanel1.add(txttitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, 30));

        txtdetail.setColumns(20);
        txtdetail.setRows(5);
        jScrollPane1.setViewportView(txtdetail);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));
        jPanel1.add(txtprix, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 170, 40));
        jPanel1.add(txtprixpromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 160, 30));

        jLabel5.setText("categorie");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        jPanel1.add(jcomboboxCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 160, -1));

        jLabel6.setText("Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 90, 40));
        jPanel1.add(txtduree, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 90, -1));
        jPanel1.add(txtNbreMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 110, -1));

        jLabel7.setText("Duree");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel8.setText("Nombre min");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel9.setText("Vendeur");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));
        jPanel1.add(jcomboboxVendeur, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 100, -1));
        jPanel1.add(txtNbreMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 100, -1));

        jLabel10.setText("Nombre max");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 220, 70));

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel1.add(annuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 210, 60));

        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-620, -580, 1280, 1120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //creation new deal dans la classe metier
         
            Deal deal =new Deal();
          
            deal.setTitre(txttitre.getText());                                                                              
            deal.setDetails(txtdetail.getText());
            deal.setPrix(Integer.parseInt(txtprix.getText()));
            deal.setPrix_promo( Integer.parseInt(txtprixpromo.getText()));
            deal.setCategorie((Categorie) jcomboboxCategorie.getSelectedItem());
            deal.setVendeur((Vendeur)jcomboboxVendeur.getSelectedItem());
            deal.setNbr_min(Integer.parseInt(txtNbreMin.getText()));
            deal.setNbr_min(Integer.parseInt(txtprixpromo.getText()));
            deal.setDate(sdf.parse(txtdate.getText()));
            
                DealMetier.AjouterDeal(deal);
            JOptionPane.showMessageDialog(null, "Del "+ deal.getTitre()+" est ajouté avec succes", "success", JOptionPane.INFORMATION_MESSAGE);
 
// TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(InterfaceAjouterDeal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        vide();
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    
   
    public void vide()
    { txttitre.setText("");
    txtdate.setText("");
    txtNbreMax.setText("");
    txtNbreMin.setText("");
    txtdetail.setText("");
    txtduree.setText("");
    
        
    }
    public void  remlirVendeur(){
        List<Vendeur> vendeur= new ArrayList<Vendeur>();
        VendeurDAO vendeurdao= new VendeurDAO();
        vendeur = vendeurdao.DisplayAllVendeur();
        for (Vendeur v:vendeur){
            jcomboboxVendeur.addItem(v.getNom());
        }
        
    }
//------------------------------------------------------
        public void remplirCategorie(){
        List <Categorie> categories=new ArrayList<Categorie>();

        CategorieDAO depotdao=new CategorieDAO();
        categories=depotdao.DisplayAllCategorie();
        for(Categorie d:categories){
            jcomboboxCategorie.addItem(d.getCategorie());
            
        
        }
        
    } 
        
        //importation du sisie ds jframe
        
      
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAjouterDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAjouterDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAjouterDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAjouterDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAjouterDeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcomboboxCategorie;
    private javax.swing.JComboBox jcomboboxVendeur;
    private javax.swing.JTextField txtNbreMax;
    private javax.swing.JTextField txtNbreMin;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextArea txtdetail;
    private javax.swing.JTextField txtduree;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtprixpromo;
    private javax.swing.JTextField txttitre;
    // End of variables declaration//GEN-END:variables
}
