/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.gui;

import edu.esprit.entities.Client;
import edu.esprit.metier.ClientMetier;
import javaapplicationstatistic.BarChartDeal;
import javaapplicationstatistic.BarChartNoteVendeur;
import javax.swing.JOptionPane;

/**
 *
 * @author nour
 */
public class InterfaceAcceuilClient extends javax.swing.JFrame {

    Client client;
    /**
     * Creates new form InterfaceAcceuilClient
     */
    public InterfaceAcceuilClient() {
        initComponents();
        
    }
    public void interClient(Client c){
        client=c;
        System.out.println(client.getEmail());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonListeDeal = new javax.swing.JButton();
        jButtonStatistiques = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jButtonStatDeal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acceuil client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 3, 18), new java.awt.Color(0, 102, 153))); // NOI18N

        jButtonListeDeal.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButtonListeDeal.setForeground(new java.awt.Color(0, 102, 153));
        jButtonListeDeal.setText("voir les deals");
        jButtonListeDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeDealActionPerformed(evt);
            }
        });

        jButtonStatistiques.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButtonStatistiques.setForeground(new java.awt.Color(0, 102, 153));
        jButtonStatistiques.setText(" voir les statistiques des vendeurs");
        jButtonStatistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatistiquesActionPerformed(evt);
            }
        });

        jButtonRetour.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButtonRetour.setForeground(new java.awt.Color(0, 102, 153));
        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jButtonStatDeal.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButtonStatDeal.setForeground(new java.awt.Color(0, 102, 153));
        jButtonStatDeal.setText("voir les statistiques des deals");
        jButtonStatDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatDealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jButtonRetour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonStatDeal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonListeDeal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonStatistiques))
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonListeDeal)
                .addGap(31, 31, 31)
                .addComponent(jButtonStatistiques)
                .addGap(18, 18, 18)
                .addComponent(jButtonStatDeal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonRetour)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
        InterfaceConnexionClient ConnClient = new InterfaceConnexionClient();
        ConnClient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButtonStatistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatistiquesActionPerformed
        // TODO add your handling code here:
        BarChartNoteVendeur barChartNote=new BarChartNoteVendeur();
        barChartNote.setVisible(true);
         
    }//GEN-LAST:event_jButtonStatistiquesActionPerformed

    private void jButtonStatDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatDealActionPerformed
        // TODO add your handling code here:
        BarChartDeal barChartDeal=new BarChartDeal();
        barChartDeal.setVisible(true);
    }//GEN-LAST:event_jButtonStatDealActionPerformed

    private void jButtonListeDealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeDealActionPerformed
        // TODO add your handling code here:
        InterfaceGestionDeal listerDeal=new InterfaceGestionDeal();
        System.out.println(client.getEmail());
        
        listerDeal.interClient(client);
        
        listerDeal.setVisible(true);
    }//GEN-LAST:event_jButtonListeDealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAcceuilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAcceuilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAcceuilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAcceuilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAcceuilClient().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonListeDeal;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonStatDeal;
    private javax.swing.JButton jButtonStatistiques;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
