/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.gui;
// les import import edu.esprit.dao.DealDAO;
import edu.esprit.entities.Client;
import edu.esprit.dao.ClientDAO ;

import java.text.ParseException;

import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;




/**
 *
 * @author mohamed amine
 */
public class interfacenscriptionInternaute extends javax.swing.JFrame {

    /**
     * Creates new form interfacenscriptionInternaute
     */
    public interfacenscriptionInternaute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtNum_tel = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        comboboxSex = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        valider_inscription = new javax.swing.JButton();
        annuler_inscription = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOM   :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setText("prenom  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setText("email  : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel4.setText("AGE  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setText("sexe :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText("NUM_TEL  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel7.setText("PASSWORD  :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        jPanel1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 30));
        jPanel1.add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 100, 30));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, 30));
        jPanel1.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 70, 30));

        txtNum_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum_telActionPerformed(evt);
            }
        });
        jPanel1.add(txtNum_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 100, 30));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 110, 30));

        comboboxSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));
        comboboxSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxSexActionPerformed(evt);
            }
        });
        jPanel1.add(comboboxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 252, 550, 10));

        valider_inscription.setText("Valider");
        valider_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_inscriptionActionPerformed(evt);
            }
        });
        jPanel1.add(valider_inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 263, -1, 40));

        annuler_inscription.setText("ANNULER");
        annuler_inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuler_inscriptionActionPerformed(evt);
            }
        });
        jPanel1.add(annuler_inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 263, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\mohamed amine\\Documents\\NetBeansProjects\\shhhhhhhih\\DevTeam\\src\\img\\addDeal.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscription_Internaute", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 640, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        /** variable de classe contenant l'image à afficher en fond */

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxSexActionPerformed

    private void txtNum_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum_telActionPerformed

    private void valider_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_inscriptionActionPerformed
        // TODO add your handling code here:
        
               ClientDAO cl = new ClientDAO();
        //CREATE NEW OBJET CLIENT
        
        Client internaute = new Client() ;
        
        //importation des champs saisie dans la jframe ;
          
        internaute.setNom(txtnom.getText());
        internaute.setPrenom(txtprenom.getText());
        
        internaute.setAge(Integer.parseInt(txtage.getText()));
        internaute.setGenre((String) comboboxSex.getSelectedItem());
        internaute.setEmail(txtemail.getText());
        internaute.setPassowrd(txtPassword.getText());
        /////////////////////////////////
        
         
    cl.insertClient(internaute);
    JOptionPane.showMessageDialog(null, "Client "+ internaute.getNom()+" est ajouté avec succes", "success", JOptionPane.INFORMATION_MESSAGE);
 
    }//GEN-LAST:event_valider_inscriptionActionPerformed

   
    private void annuler_inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuler_inscriptionActionPerformed
        // TODO add your handling code here:
        /*
      annuler_inscription()
        
        
        public void annuler_inscription()
      { txtnom.seText ="";
         txtprenom.
      
      }
        */
        
        
      
        
        
    }//GEN-LAST:event_annuler_inscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfacenscriptionInternaute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfacenscriptionInternaute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfacenscriptionInternaute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfacenscriptionInternaute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfacenscriptionInternaute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler_inscription;
    private javax.swing.JComboBox comboboxSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtNum_tel;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JButton valider_inscription;
    // End of variables declaration//GEN-END:variables
}

/*
public void annuler_inscription(

{

txtnom="";
        txtprenom="";
        txtage ="";
        txtNum_tel="";
        txtPassword="";
        txtemail="";
        
}
}
*/